create or replace PROCEDURE FIND_HOTEL_ID (I_STREET_NAME VARCHAR, I_CITY_NAME VARCHAR, I_STATE_CODE VARCHAR,I_ZIP_CODE VARCHAR ) AS 
V_HOTEL_ID HOTEL.HOTEL_ID%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('-- FIND_HOTEL_ID');
    DBMS_OUTPUT.PUT_LINE('STREET NAME : ' || I_STREET_NAME);
    DBMS_OUTPUT.PUT_LINE('CITY NAME   : ' || I_CITY_NAME);
    DBMS_OUTPUT.PUT_LINE('STATE CODE  : ' || I_STATE_CODE);
    DBMS_OUTPUT.PUT_LINE('ZIP CODE    : ' || I_ZIP_CODE);

    IF I_STREET_NAME IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20010, 'INVALID STREET NAME : CANNOT BE NULL');
    END IF;

    IF I_CITY_NAME IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20020, 'INVALID CITY NAME: CANNOT BE NULL');
    END IF;

    IF I_STATE_CODE IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20030, 'INVALID STATE CODE : CANNOT BE NULL');
    END IF;

    IF I_ZIP_CODE IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20030, 'INVALID ZIP CODE : CANNOT BE NULL');
    END IF;

    SELECT HOTEL_ID INTO V_HOTEL_ID FROM HOTEL
    WHERE STREET_NAME = I_STREET_NAME 
    AND CITY_NAME = I_CITY_NAME
    AND STATE_CODE = I_STATE_CODE
    AND ZIP_CODE = I_ZIP_CODE;

     DBMS_OUTPUT.PUT_LINE('HOTEL_ID: ' || V_HOTEL_ID);
     DBMS_OUTPUT.PUT_LINE('-- FIND_HOTEL_ID SUCCESSFUL');

EXCEPTION
    when no_data_found then
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    dbms_output.put_line('-- NO SUCH HOTEL PRESENT');
    RAISE;
    when too_many_rows then
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    dbms_output.put_line('too many rows');
    RAISE;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE('-- FIND_HOTEL_ID - FAILED');
    RAISE;

END FIND_HOTEL_ID;
