--Input- Customer's name,Hote_ID,start and end_date
--Output- Displays the Reservation_ID booked by the customer for the concerned date and Preferred Hotel.

create or replace FUNCTION FIND_RESERVATION_ID(I_CUSTOMER_NAME IN VARCHAR, I_STREET_NAME IN VARCHAR, I_CITY_NAME IN VARCHAR, 
        I_STATE_CODE IN VARCHAR, I_ZIP_CODE IN VARCHAR, I_START_DATE IN DATE, I_END_DATE IN DATE) RETURN integer AS 
        
    CURSOR DISPLAY_EVENT_RESERVATION (C_CUSTOMER_NAME VARCHAR, C_HOTEL_ID IN VARCHAR, C_START_DATE DATE, C_END_DATE DATE) IS 
       select events.reservation_id from EVENTS ,CUSTOMERS 
		where events.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID  
        AND EVENTS.HOTEL_ID = C_HOTEL_ID
        AND EVENTS.START_DATE = C_START_DATE
        AND EVENTS.END_DATE = C_END_DATE
        AND CUSTOMERS.CUSTOMER_NAME = C_CUSTOMER_NAME;

V_HOTEL_ID HOTEL.HOTEL_ID%TYPE;
V_RESERVATION_ID EVENTS.RESERVATION_ID%TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('-- FIND RESERVATION ID');
    IF I_CUSTOMER_NAME IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20010, 'INVALID CUSTOMER NAME : CANNOT BE NULL');
    END IF;		

	IF I_START_DATE IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20010, 'INVALID START DATE : CANNOT BE NULL');
    END IF;	

	IF I_END_DATE IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20010, 'INVALID END DATE : CANNOT BE NULL');
    END IF;		

    V_HOTEL_ID := FIND_A_HOTEL(I_STREET_NAME, I_CITY_NAME, I_STATE_CODE, I_ZIP_CODE);

    OPEN DISPLAY_EVENT_RESERVATION (I_CUSTOMER_NAME, V_HOTEL_ID, I_START_DATE, I_END_DATE);
    LOOP

    FETCH DISPLAY_EVENT_RESERVATION INTO V_RESERVATION_ID;
    EXIT WHEN DISPLAY_EVENT_RESERVATION%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('RESERVATION ID: ' || V_RESERVATION_ID);
    END LOOP;

    CLOSE DISPLAY_EVENT_RESERVATION;
    RETURN V_RESERVATION_ID;
     DBMS_OUTPUT.PUT_LINE('-- FIND_RESERVATION_ID - SUCCESSFUL');

EXCEPTION
    When no_data_found then
	dbms_output.put_line(' There is no such Event Reservation ID');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE('-- FIND_EVENT_RESERVATION - FAILED');
    RAISE;
END FIND_RESERVATION_ID;
