--INPUT PARAMETERS-Hotel address with customer email and name and the number of people attending ,event type and name
--OUTPUT PARAMETER-New reservation id if the room is available else no available rooms
create or replace PROCEDURE MAKE_EVENT_RESERVATION(
    I_STREET_NAME VARCHAR, I_CITY_NAME VARCHAR, I_STATE_CODE VARCHAR,I_ZIP_CODE VARCHAR,
    I_CUSTOMER_NAME IN VARCHAR,
    I_EMAIL VARCHAR,
    I_START_DATE IN DATE,
    I_END_DATE IN DATE,
    I_EVENT_TYPE IN VARCHAR,
    I_PPL_NO IN NUMBER,
    I_EVENT_NAME VARCHAR
    ) AS 
    V_HOTEL_ID NUMBER;
    V_RES_ID NUMBER;
    V_SMALL_CT NUMBER;
    V_MED_CT NUMBER;
    V_LARGE_CT NUMBER;

    V_PREF_ROOM_TYPE EVENT_ROOM1.ROOM_TYPE%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('---- MAKE EVENT RESERVATION STARTING ----');

    -- GET HOTEL ID BY CALLING A FUNCTION
    V_HOTEL_ID := FIND_A_HOTEL(I_STREET_NAME, I_CITY_NAME, I_STATE_CODE,I_ZIP_CODE);


   DBMS_OUTPUT.PUT_LINE('PRINT HOTEL ID'|| V_HOTEL_ID);


    -- GET COUNT OF AVAILABLE ROOMS BY CALLING A SUB-PROCEDURE
    SHOW_AVAILABLE_ROOMS(V_HOTEL_ID,I_START_DATE,I_END_DATE,V_LARGE_CT,V_MED_CT,V_SMALL_CT);

    -- LOOP on date
    -- FIND Room Availability for all Room Types
    -- Find minimum number of rooms to satisfy total people count
    -- Book room for the date
    -- Increment date
    -- Continue if less than end date

    CASE TRUE 
    WHEN I_PPL_NO <= 100 AND (V_SMALL_CT > 0 OR V_MED_CT > 0 OR V_LARGE_CT > 0) THEN

    IF V_SMALL_CT > 0 THEN V_PREF_ROOM_TYPE := 'SMALL HALL';
    ELSIF V_MED_CT > 0 THEN V_PREF_ROOM_TYPE := 'MEDIUM HALL';
    ELSE V_PREF_ROOM_TYPE := 'LARGE HALL';
    END IF;

    V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
    I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,V_PREF_ROOM_TYPE);

    WHEN I_PPL_NO > 100 AND I_PPL_NO <= 200 AND (V_SMALL_CT >= 2 OR V_MED_CT > 0 OR V_LARGE_CT > 0) THEN

    IF V_SMALL_CT >= 2 THEN 
        V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
            I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'SMALL HALL');

        V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
            I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'SMALL HALL');
    ELSIF V_MED_CT > 0 THEN 
        V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
        I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'MEDIUM HALL');        
    ELSE 
        V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
            I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'LARGE HALL');

    END IF;

    WHEN I_PPL_NO > 100 AND I_PPL_NO < 250 AND V_MED_CT > 0 THEN
    V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
    I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'MEDIUM HALL');

    WHEN I_PPL_NO > 250 AND I_PPL_NO <= 500 AND V_LARGE_CT > 0 THEN
   V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
    I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'LARGE HALL');

    WHEN I_PPL_NO > 500 AND I_PPL_NO <= 1000 AND V_LARGE_CT >= 2 THEN
    V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
    I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'LARGE HALL');

    V_RES_ID := INSERT_RES(I_CUSTOMER_NAME, I_EMAIL, I_START_DATE,
    I_END_DATE,I_EVENT_TYPE, I_PPL_NO, V_HOTEL_ID,I_EVENT_NAME,'LARGE HALL');

    ELSE 
    DBMS_OUTPUT.PUT_LINE('NO ROOMS AVAILABLE');

    END CASE;

    DBMS_OUTPUT.PUT_LINE ('BOOKING CONFIRMED. RESERVATION ID IS: ' || V_RES_ID);
    DBMS_OUTPUT.PUT_LINE ('-- MAKE EVENT RESERVATION SUCESSFULL --');

EXCEPTION    

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE('-- MAKE_EVENT_RESERVATION - FAILED');


END MAKE_EVENT_RESERVATION;

