CREATE OR REPLACE PROCEDURE REPORT_HOTEL_N_ROOM_STATE(CITY_GIVEN IN VARCHAR,STATE_GIVEN IN VARCHAR)
IS
CURSOR C1 IS SELECT E.ROOM_ID1,E.ROOM_TYPE,R.ROOM_CAPACITY,E.HOTEL_ID,H.HOTEL_NAME,H.STREET_NAME,H.CITY_NAME,H.STATE_CODE,H.ZIP_CODE 
FROM EVENT_ROOM1 E,HOTEL  H, ROOM R
WHERE H.STATE_CODE=STATE_GIVEN AND H.CITY_NAME=CITY_GIVEN AND E.HOTEL_ID = H.HOTEL_ID AND R.ROOM_TYPE=E.ROOM_TYPE;

O_ROOM_ID NUMBER;
O_ROOM_TYPE VARCHAR(25);
O_CAPACITY1 NUMBER;
O_HOTEL_ID NUMBER;
O_HOTEL_NAME VARCHAR(35);
O_STREET_NAME VARCHAR(25);
O_CITY_NAME VARCHAR(35);
O_STATE_CODE VARCHAR(3);
O_ZIP_CODE VARCHAR(7);

BEGIN
OPEN C1;
LOOP
FETCH C1 INTO O_ROOM_ID,O_ROOM_TYPE,O_CAPACITY1,O_HOTEL_ID,O_HOTEL_NAME,O_STREET_NAME,O_CITY_NAME,O_STATE_CODE,O_ZIP_CODE;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('HOTEL ID IS:'||O_HOTEL_ID || ' HOTEL NAME IS: ' || O_HOTEL_NAME || ' (ADDRESS: '|| O_STREET_NAME || ', '  || O_CITY_NAME||', '|| O_STATE_CODE ||', '|| O_ZIP_CODE||')'); 

DBMS_OUTPUT.PUT_LINE('EVENT ROOM ID: '||O_ROOM_ID || ' '||'ROOM TYPE: '||O_ROOM_TYPE ||' ' || '& '||'ROOM CAPACITY IS: '||O_CAPACITY1 );

END LOOP;
CLOSE C1;

END REPORT_HOTEL_N_ROOM_STATE;