create or replace PROCEDURE SERVICES_INCOME_REPORT(I_STREET_NAME VARCHAR, I_CITY_NAME VARCHAR, I_STATE_CODE VARCHAR,I_ZIP_CODE VARCHAR) AS  
    
    CURSOR RESID_BY_HOTEL(C_HOTEL_ID INTEGER) IS
    SELECT RESERVATION_ID FROM EVENTS
    WHERE HOTEL_ID = C_HOTEL_ID;
    
    V_HOTEL_ID HOTEL.HOTEL_ID%TYPE;
    V_CURSOR_DATA EVENTS.RESERVATION_ID%TYPE;
    V_INCOME_BY_RESID NUMBER := 0;
    V_TOTAL_INCOME NUMBER := 0;

    
BEGIN

    DBMS_OUTPUT.PUT_LINE('-- SERVICES_INCOME_REPORT --');
    

    V_HOTEL_ID := FIND_A_HOTEL(I_STREET_NAME, I_CITY_NAME, I_STATE_CODE, I_ZIP_CODE); 

    
    OPEN RESID_BY_HOTEL(V_HOTEL_ID);
    LOOP
        FETCH RESID_BY_HOTEL INTO V_CURSOR_DATA;
        EXIT WHEN RESID_BY_HOTEL%NOTFOUND;
            V_INCOME_BY_RESID := SERVICE_INCOME_BY_RESID(V_CURSOR_DATA);
            V_TOTAL_INCOME := V_TOTAL_INCOME + V_INCOME_BY_RESID;
    END LOOP;
    CLOSE RESID_BY_HOTEL;
    
    DBMS_OUTPUT.PUT_LINE('INCOME FROM SERVICES IN ALL RESERVATIONS IN THE GIVEN HOTEL IS: ' 
                             || V_TOTAL_INCOME);    
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE('--SERVICES_INCOME_REPORT - FAILED --');
        RAISE;
END SERVICES_INCOME_REPORT;