create or replace PROCEDURE SHOW_SPECIFIC_SERVICE_REPORT(I_SERVICE_TYPE IN VARCHAR) AS 

CURSOR EXTRACT_EVENT_DETAILS (C_SERVICE_TYPE VARCHAR) IS
    SELECT E.RESERVATION_ID, E.EVENT_TYPE, E.START_DATE, E.END_DATE, E.EVENT_STATUS, H.HOTEL_NAME
    FROM EVENTS E, SERVICERESERVATION S, HOTEL H 
    WHERE E.RESERVATION_ID = S.RESERVATION_ID 
    AND E.HOTEL_ID = H.HOTEL_ID
    AND S.SERVICE_TYPE = C_SERVICE_TYPE;

    V_CURSOR_DATA EXTRACT_EVENT_DETAILS%ROWTYPE;
    V_SERVICE_TYPE SERVICE.SERVICE_TYPE%TYPE;

BEGIN
    DBMS_OUTPUT.PUT_LINE('-- SHOW_SPECIFIC_SERVICE_REPORT');
    DBMS_OUTPUT.PUT_LINE('SERVICE NAME: ' || I_SERVICE_TYPE);
    
    IF I_SERVICE_TYPE IS NULL
    THEN
        RAISE_APPLICATION_ERROR(-20010, 'INVALID SERVICE NAME : CANNOT BE NULL');
    END IF;
    
    BEGIN
        SELECT SERVICE_TYPE INTO V_SERVICE_TYPE
        FROM SERVICE
        WHERE SERVICE_TYPE = I_SERVICE_TYPE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20020, 'INVALID SERVICE NAME : SERVICE_TYPE [' || I_SERVICE_TYPE 
                                            || '] NOT FOUND IN SERVICE TABLE');
    END;
    
    DBMS_OUTPUT.PUT_LINE('RESERVATIONS THAT OPTED FOR THE SERVICE ' || I_SERVICE_TYPE || ' ARE: '); 
    DBMS_OUTPUT.PUT_LINE(LPAD('RESERVATION_ID',15)||LPAD('EVENT NAME',20)||LPAD('START DATE',12)||
                         LPAD('END DATE', 12)||LPAD('EVENT STATUS', 12)||' HOTEL NAME');
    
    OPEN EXTRACT_EVENT_DETAILS(I_SERVICE_TYPE);
    LOOP
        FETCH EXTRACT_EVENT_DETAILS INTO V_CURSOR_DATA;
        EXIT WHEN EXTRACT_EVENT_DETAILS%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE(LPAD(V_CURSOR_DATA.RESERVATION_ID,15)||LPAD(V_CURSOR_DATA.EVENT_TYPE, 20) || 
                            LPAD(V_CURSOR_DATA.START_DATE, 12) || LPAD(V_CURSOR_DATA.END_DATE, 12) ||
                            LPAD(V_CURSOR_DATA.EVENT_STATUS, 12) || ' ' ||  V_CURSOR_DATA.HOTEL_NAME);
    END LOOP;
    CLOSE EXTRACT_EVENT_DETAILS;
    
    DBMS_OUTPUT.PUT_LINE('--SHOW_SPECIFIC_SERVICE_REPORT - SUCCESSFUL ');
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE('-- SHOW_SPECIFIC_SERVICE_REPORT - FAILED');
        RAISE;
END SHOW_SPECIFIC_SERVICE_REPORT;