--input- no input parameter
--output-Cancels event

create or replace PROCEDURE SHOW_CANCELATION AS 
CURSOR CANCELLEDEVENT IS
    SELECT E.RESERVATION_ID,E.START_DATE,E.END_DATE,H.HOTEL_NAME,H.STREET_NAME,H.CITY_NAME,H.STATE_CODE,H.ZIP_CODE,RR.ROOM_TYPE
    FROM EVENTS E,HOTEL H,ROOMRESERVATION RR 
    WHERE E.HOTEL_ID=H.HOTEL_ID AND
    E.RESERVATION_ID=RR.RESERVATION_ID AND
    E.EVENT_STATUS='0';
    V_CURDATA CANCELLEDEVENT%ROWTYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--SHOW CANCELLATION---');
   open CANCELLEDEVENT; 
loop
fetch CANCELLEDEVENT into V_CURDATA;
EXIT WHEN CANCELLEDEVENT%NOTFOUND;

DBMS_OUTPUT.PUT_LINE('EVENT RESERVATION ID:'|| V_CURDATA.RESERVATION_ID);
DBMS_OUTPUT.PUT_LINE('EVENT DATE:'|| V_CURDATA.START_DATE||' TO '|| V_CURDATA.END_DATE);
DBMS_OUTPUT.PUT_LINE('HOTEL NAME:'|| V_CURDATA.HOTEL_NAME);
DBMS_OUTPUT.PUT_LINE('HOTEL ADDRESS:'|| V_CURDATA.STREET_NAME||','||V_CURDATA.CITY_NAME||','||V_CURDATA.STATE_CODE||'-'||V_CURDATA.ZIP_CODE);
DBMS_OUTPUT.PUT_LINE('HOTEL NAME:'|| V_CURDATA.HOTEL_NAME);
DBMS_OUTPUT.PUT_LINE('ROOM TYPE:'|| V_CURDATA.ROOM_TYPE);
DBMS_OUTPUT.PUT_LINE('----------------------------------------------');

END LOOP;
CLOSE CANCELLEDEVENT;

DBMS_OUTPUT.PUT_LINE('---SHOW CANCELLATION SUCCESSFUL---');

EXCEPTION    

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE('-- ADD_SERVICE_TO_EVENT - FAILED');
        RAISE;


END SHOW_CANCELATION;
