CREATE OR REPLACE PROCEDURE SHOW_ROOM(HOTELID_GIVEN IN NUMBER) IS
ROOM_COUNT INT;
ROOM_O_TYPE VARCHAR(15);

CURSOR C1 IS SELECT COUNT(*),ROOM_TYPE 
FROM EVENT_ROOM1 R
WHERE R.HOTEL_ID=HOTELID_GIVEN
GROUP BY(ROOM_TYPE);
BEGIN
DBMS_OUTPUT.PUT_LINE('INFORMATION ON HOTEL EVENT ROOMS');
DBMS_OUTPUT.PUT_LINE('GIVEN HOTEL ID IS:' || HOTELID_GIVEN);
OPEN C1;
LOOP
FETCH C1 INTO ROOM_COUNT,ROOM_O_TYPE;
EXIT WHEN C1%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('COUNT FOR '||ROOM_O_TYPE||' TYPE IS '||ROOM_COUNT);
END LOOP;
CLOSE C1;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
DBMS_OUTPUT.PUT_LINE('NO SUCH HOTEL PRESENT');
RAISE;
WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
DBMS_OUTPUT.PUT_LINE('TOO MANY ROWS');
RAISE;
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE(SQLERRM);
DBMS_OUTPUT.PUT_LINE('-- SHOW_ROOM - FAILED');
RAISE;
END SHOW_ROOM;
