create or replace FUNCTION ROOM_INCOME_BY_RESID(I_RESERVATION_ID IN
VARCHAR)
RETURN NUMBER AS
V_ROOM_COST NUMBER;
BEGIN
DBMS_OUTPUT.PUT_LINE('-- ROOM_INCOME_BY_RESID FUNCTION');
VALIDATE_RES_ID(I_RESERVATION_ID);
SELECT SUM(R.ROOM_PRICE) INTO V_ROOM_COST
FROM ROOMRESERVATION RR, EVENTS E, ROOM R
WHERE RR.RESERVATION_ID = E.RESERVATION_ID
AND RR.ROOM_TYPE = R.ROOM_TYPE
AND E.RESERVATION_ID = I_RESERVATION_ID
GROUP BY E.RESERVATION_ID;
DBMS_OUTPUT.PUT_LINE('-- ROOM_INCOME_BY_RESID : RESERVATION_ID : ' ||
I_RESERVATION_ID || ' : TOTAL ROOM COST : ' || V_ROOM_COST);
RETURN V_ROOM_COST;
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('-- ROOM_INCOME_BY_RESID : NO ROOM
RESERVATION FOUND FOR REGISTRATION : ' || I_RESERVATION_ID);
RAISE;
WHEN OTHERS THEN
RAISE;
END ROOM_INCOME_BY_RESID;
